### PR TITLE
Don't raise exception, fail the workflow

### PR DESCRIPTION
**Pull request by agrare**
We should mark the workflow as failed not raise out of the state

### CODE REVIEW

**Comment by Fryguy** [comment]
Why is activesupport in here?  I don't see anything here where we need it

**Comment by agrare** [comment]
@Fryguy https://github.com/ManageIQ/floe/pull/114

**Comment by kbrock** [comment]
@fryguy #116

**Comment by Fryguy** [comment]
Ok, merged #114 - I like the removal of it til we actually need it.

**Pull request merged**
