### PR TITLE
reduce complexity ContainerRunner#resolve_cli_options

### PR DESCRIPTION
**Pull request by kbrock**
not sure this is necessary

But it the comment 'shortcut support' suggests putting this in a method works

### CODE REVIEW

**Comment by kbrock** [comment]
can't believe even introducing this simple method it is too "complex"

going forward ignoring the code climate issue around this method

**Comment by Fryguy** [comment]
@kbrock This is what I was referring too where we bumped the value to higher than 5: https://github.com/ManageIQ/manageiq-style/blob/master/styles/cc_base.yml#L36-L38 .  I'm curious why this is not being honored in codeclimate.

**Comment by kbrock** [comment]
@Fryguy it feels like the bash prompt `rubocop` follows slightly different rules than miq-bot

**Comment by Fryguy** [comment]
That's correct, we have different ones for code climate (which only looks at metrics) and the bot (which only looks at style)

**Pull request closed without merging**
